Ejercicios de repaso sobre creación de arrays de multiples dimensiones usando la libreria Numpy.

In [2]:
#EJERCICIO 2

import numpy as np

# 1. Crear un array unidimensional con los nombres de los productos
productos = np.array(["Smartphone", "Tablet", "Laptop", "Auriculares", "Teclado"])
print("Array de productos:", productos)

# 2. Crear un array bidimensional con el stock de productos en diferentes almacenes
stock = np.array([
    [50, 30, 20],  # Smartphone
    [30, 20, 25],  # Tablet
    [15, 10, 12],  # Laptop
    [40, 35, 30],  # Auriculares
    [60, 50, 55]   # Teclado
])
print("\nStock en diferentes almacenes:\n", stock)

# 3. Crear un array tridimensional para registrar las ventas durante la semana
ventas = np.array([
    [5, 3, 2, 6, 4],  # Día 1
    [7, 4, 1, 8, 5],  # Día 2
    [6, 2, 3, 5, 4]   # Día 3
])
print("\nVentas durante 3 días:\n", ventas)

# 4. Crear un array de ceros para los productos no vendidos hoy
productos_no_vendidos = np.zeros(5, dtype=int)
print("\nProductos no vendidos hoy:", productos_no_vendidos)

# 5. Crear un array de unos para los productos en promoción
productos_en_promocion = np.array([1, 0, 0, 0, 1])  # Smartphone y Teclado
print("\nProductos en promoción:", productos_en_promocion)

# 6. Crear un array con un rango de precios de productos (50 a 1000 con paso de 50)
rango_precios = np.arange(50, 1050, 50)
print("\nRango de precios de productos:", rango_precios)

# 7. Crear un array de precios aleatorios para los productos (entre 100 y 500)
precios_aleatorios = np.random.randint(100, 501, size=5)
print("\nPrecios aleatorios:", precios_aleatorios)

# 8. Crear un array de números enteros aleatorios para la cantidad vendida hoy
cantidad_vendida_hoy = np.random.randint(1, 11, size=5)
print("\nCantidad vendida hoy:", cantidad_vendida_hoy)

# 9. Crear un array vacío para almacenar valores de descuento
descuentos = np.empty((5, 1))
print("\nArray vacío para descuentos:\n", descuentos)

# 10. Generar un array con valores espaciados para analizar el cambio en las ventas
ventas_totales_dia = np.linspace(0, 1000, 5)
print("\nCambio en ventas durante el día:", ventas_totales_dia)

Array de productos: ['Smartphone' 'Tablet' 'Laptop' 'Auriculares' 'Teclado']

Stock en diferentes almacenes:
 [[50 30 20]
 [30 20 25]
 [15 10 12]
 [40 35 30]
 [60 50 55]]

Ventas durante 3 días:
 [[5 3 2 6 4]
 [7 4 1 8 5]
 [6 2 3 5 4]]

Productos no vendidos hoy: [0 0 0 0 0]

Productos en promoción: [1 0 0 0 1]

Rango de precios de productos: [  50  100  150  200  250  300  350  400  450  500  550  600  650  700
  750  800  850  900  950 1000]

Precios aleatorios: [325 453 394 255 316]

Cantidad vendida hoy: [2 5 6 1 3]

Array vacío para descuentos:
 [[4.70822572e-310]
 [0.00000000e+000]
 [4.70822406e-310]
 [4.70822406e-310]
 [2.37151510e-322]]

Cambio en ventas durante el día: [   0.  250.  500.  750. 1000.]


In [3]:
#EJERCICIO 3

# 1. Creación de arrays

# Array 1D con los números del 1 al 10
array_1d = np.arange(1, 11)
print("Array 1D:", array_1d)

# Array 2D de tamaño 3x3 con valores del 1 al 9
array_2d = np.arange(1, 10).reshape(3, 3)
print("\nArray 2D:\n", array_2d)

# 2. Indexación en arrays

# Primer y último elemento del array 1D
primero_1d = array_1d[0]
ultimo_1d = array_1d[-1]
print("\nPrimer elemento del array 1D:", primero_1d)
print("Último elemento del array 1D:", ultimo_1d)

# Primer elemento de la primera fila del array 2D
primero_2d = array_2d[0, 0]
print("\nPrimer elemento de la primera fila del array 2D:", primero_2d)

# Último elemento de la última fila del array 2D
ultimo_2d = array_2d[-1, -1]
print("Último elemento de la última fila del array 2D:", ultimo_2d)

# Elemento en la segunda fila y tercera columna del array 2D
elemento_2d = array_2d[1, 2]
print("Elemento en la segunda fila y tercera columna del array 2D:", elemento_2d)

# 3. Selección de filas y columnas

# Primera fila completa del array 2D
primera_fila = array_2d[0, :]
print("\nPrimera fila completa del array 2D:", primera_fila)

# Segunda columna completa del array 2D
segunda_columna = array_2d[:, 1]
print("Segunda columna completa del array 2D:", segunda_columna)

Array 1D: [ 1  2  3  4  5  6  7  8  9 10]

Array 2D:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Primer elemento del array 1D: 1
Último elemento del array 1D: 10

Primer elemento de la primera fila del array 2D: 1
Último elemento de la última fila del array 2D: 9
Elemento en la segunda fila y tercera columna del array 2D: 6

Primera fila completa del array 2D: [1 2 3]
Segunda columna completa del array 2D: [2 5 8]


In [ ]:
#EJERCICIO 4

# 1. Creación del array 3D

# Generar un array 3D de tamaño 4x4x3 con valores aleatorios entre 0 y 255
imagen_rgb = np.random.randint(0, 256, size=(4, 4, 3), dtype=np.uint8)
print("Array 3D (imagen RGB):\n", imagen_rgb)

# 2. Indexación en el array 3D

# Primer píxel (posición [0, 0]) con sus valores de color (R, G, B)
primer_pixel = imagen_rgb[0, 0, :]
print("\nPrimer píxel (posición [0, 0]):", primer_pixel)

# Último píxel de la imagen (posición [-1, -1])
ultimo_pixel = imagen_rgb[-1, -1, :]
print("Último píxel (posición [-1, -1]):", ultimo_pixel)

# Valor del canal rojo del píxel en la segunda fila y tercera columna
canal_rojo_pixel = imagen_rgb[1, 2, 0]
print("Valor del canal rojo del píxel [1, 2]:", canal_rojo_pixel)

# 3. Slicing en el array 3D

# Toda la primera fila de la imagen (todos los píxeles con sus valores RGB)
primera_fila = imagen_rgb[0, :, :]
print("\nPrimera fila completa (valores RGB):\n", primera_fila)

# Solo los valores del canal azul para todos los píxeles de la imagen
canal_azul = imagen_rgb[:, :, 2]
print("\nCanal azul de toda la imagen:\n", canal_azul)

# Recorte central de la imagen (filas y columnas intermedias)
recorte_central = imagen_rgb[1:3, 1:3, :]
print("\nRecorte central de la imagen (valores RGB):\n", recorte_central)

Array 3D (imagen RGB):
 [[[211  15  94]
  [196 219  42]
  [179  80 125]
  [235  23 210]]

 [[123 224  29]
  [112 207 117]
  [130  87 199]
  [196  32   3]]

 [[131 141 192]
  [176  31  28]
  [  6 249  82]
  [163 117 204]]

 [[156 153  76]
  [ 73 111  46]
  [105 254  90]
  [ 39 251  89]]]

Primer píxel (posición [0, 0]): [211  15  94]
Último píxel (posición [-1, -1]): [ 39 251  89]
Valor del canal rojo del píxel [1, 2]: 130

Primera fila completa (valores RGB):
 [[211  15  94]
 [196 219  42]
 [179  80 125]
 [235  23 210]]

Canal azul de toda la imagen:
 [[ 94  42 125 210]
 [ 29 117 199   3]
 [192  28  82 204]
 [ 76  46  90  89]]

Recorte central de la imagen (valores RGB):
 [[[112 207 117]
  [130  87 199]]

 [[176  31  28]
  [  6 249  82]]]


In [5]:
#EJERCICIO 5

# Crear los dos puntos en un espacio de 5 dimensiones
punto1 = np.array([2, 3, 5, 7, 11])
punto2 = np.array([1, 4, 6, 8, 10])

# Calcular la distancia euclidiana entre los puntos
distancia = np.linalg.norm(punto1 - punto2)

print("Distancia euclidiana entre los dos puntos:", distancia)

Distancia euclidiana entre los dos puntos: 2.23606797749979


In [6]:
#EJERCICIO 6

#Evaluación rendimiento calificación estudiantes usando Norma L2 (Distancia Euclidiana)

#Datos de entrada
calificaciones = np.array([
    [88, 78, 64, 92, 57, 70, 88, 68, 72, 60],
    [60, 73, 85, 89, 73, 52, 71, 51, 73, 93],
    [79, 87, 51, 70, 82, 61, 71, 93, 74, 98],
    [76, 91, 77, 65, 64, 96, 93, 52, 86, 56],
    [70, 58, 88, 67, 53, 74, 63, 99, 58, 75],
    [82, 79, 91, 88, 66, 78, 79, 63, 59, 89],
    [56, 66, 73, 77, 75, 80, 70, 64, 88, 60],
    [80, 62, 79, 85, 92, 72, 80, 69, 78, 66],
    [88, 90, 69, 77, 66, 72, 65, 73, 92, 81],
    [60, 80, 69, 94, 81, 88, 93, 60, 58, 79],
    [78, 72, 74, 81, 67, 93, 60, 72, 85, 92],
    [86, 90, 70, 64, 93, 58, 61, 95, 79, 84],
    [85, 77, 91, 85, 61, 63, 58, 68, 65, 90],
    [71, 79, 69, 58, 75, 78, 62, 82, 77, 59],
    [87, 76, 72, 68, 88, 65, 75, 90, 69, 79],
    [78, 71, 94, 67, 72, 88, 58, 79, 91, 67],
    [67, 64, 85, 81, 70, 84, 79, 73, 62, 77],
    [90, 61, 60, 91, 72, 89, 77, 75, 76, 83],
    [94, 83, 80, 59, 65, 75, 63, 92, 68, 60],
    [80, 81, 68, 95, 72, 93, 89, 59, 81, 85],
    [88, 63, 90, 77, 69, 72, 85, 78, 61, 93],
    [91, 65, 79, 92, 63, 74, 87, 70, 92, 85],
    [92, 80, 76, 72, 81, 87, 64, 74, 70, 67],
    [72, 83, 91, 58, 67, 88, 81, 76, 74, 92],
    [84, 91, 81, 77, 80, 63, 70, 79, 89, 65],
    [66, 65, 77, 58, 79, 61, 86, 72, 64, 74],
    [94, 74, 83, 89, 77, 68, 81, 92, 70, 68],
    [73, 72, 82, 80, 79, 64, 69, 60, 76, 79],
    [82, 79, 75, 89, 85, 81, 62, 64, 60, 92],
    [87, 88, 80, 74, 85, 90, 75, 68, 68, 71],
    [81, 79, 85, 76, 64, 85, 71, 77, 67, 93],
    [82, 89, 77, 72, 66, 84, 92, 60, 67, 65],
    [90, 63, 94, 67, 88, 93, 79, 64, 88, 80],
    [81, 90, 72, 76, 74, 93, 88, 84, 80, 65],
    [86, 75, 67, 81, 93, 79, 91, 64, 78, 74],
    [69, 85, 90, 91, 60, 76, 84, 78, 74, 64],
    [67, 91, 94, 78, 81, 73, 62, 67, 60, 92],
    [85, 79, 73, 60, 85, 90, 82, 75, 74, 68],
    [91, 83, 77, 92, 74, 68, 64, 92, 90, 92],
    [65, 93, 88, 82, 92, 67, 79, 68, 81, 93],
    [92, 79, 90, 92, 72, 80, 61, 75, 86, 90],
    [80, 67, 76, 84, 92, 90, 79, 93, 74, 88],
    [60, 79, 90, 93, 64, 61, 85, 76, 92, 72],
    [88, 67, 72, 64, 80, 90, 79, 75, 85, 81],
    [79, 92, 75, 72, 92, 81, 79, 70, 68, 68],
    [65, 60, 79, 89, 79, 82, 86, 64, 60, 81],
    [92, 81, 60, 79, 94, 78, 80, 91, 85, 68],
    [79, 64, 81, 72, 68, 75, 80, 94, 79, 61],
    [79, 94, 64, 89, 80, 85, 74, 82, 65, 91]
])

rendimientoAsignatura = np.linalg.norm(calificaciones, axis=0, keepdims=True)
rendimientoEstudiante = np.linalg.norm(calificaciones, axis=1)

print("Rendimiento por asignatura: ", rendimientoAsignatura)
print("Rendimiento por estudiante: ", rendimientoEstudiante)

#vectorNormalizado = calificaciones / np.linalg.norm(calificaciones)
#print(vectorNormalizado) 

#for i in calificaciones:
#    rendimientoEstudiante = np.linalg.norm(i)
#    for x in i:
#        rendimiento = np.linalg.norm(x)
#        print("El rendimiento por asignatura será: \n", rendimiento)

Rendimiento por asignatura:  [[560.86986013 545.80032979 551.05807316 552.24632185 534.66905652
  549.20032775 534.83455386 529.10395954 528.89129318 549.85179821]]
Rendimiento por estudiante:  [235.98516903 231.79301111 246.02032436 243.73756379 227.02643018
 247.06679259 226.08626672 242.8147442  246.27829787 244.45040397
 246.81166909 250.09598158 238.03991262 226.0398195  244.64055265
 244.44426768 235.94490882 247.03441056 236.88182708 256.18547968
 247.72161795 254.58593834 242.72412323 249.45540684 247.95765768
 223.57996332 253.42454498 233.13515393 245.56261931 249.8559585
 247.45100525 240.72390824 257.42571744 255.286114   250.79473679
 245.875985   244.90202122 245.29370151 262.27275878 257.62375667
 260.18262817 261.52437745 247.09512338 248.32438463 246.83597793
 237.91805312 257.51893134 239.85203772 255.78311125]


In [ ]:
#EJERCICIO 7

# Definición de los vectores
v1 = np.array([3, 4, 0])  # Vector de vuelo previsto
v2 = np.array([4, 3, 1])  # Vector de vuelo real

# Cálculo del producto cruzado
producto_cruzado = np.cross(v1, v2)
print(producto_cruzado)

[ 4 -3 -7]


1.	Dirección de la desviación:

El producto cruzado genera un vector perpendicular al plano definido por \mathbf{v1} y \mathbf{v2}. En este caso, la dirección [4, -3, -7] indica la dirección de desviación con respecto al plano de vuelo previsto.

2.	Corrección de la trayectoria:

Para alinear el avión con la trayectoria prevista (\mathbf{v1}):
    Se deben reducir las componentes del desvío que se ven reflejadas en la dirección [4, -3, -7].
	Ajustes en los sistemas de control del avión (motores o alerones) podrían realizarse proporcionalmente a las magnitudes 4, -3, y -7, compensando así la fuerza desviadora.

In [8]:
#EJERCICIO 8

# Representación de los datos en NumPy
tiempos_atleta = np.array([11, 22, 50, 110, 250])  # Tiempos del atleta en segundos
importancia_pruebas = np.array([0.4, 0.3, 0.2, 0.1, 0.05])  # Importancia de cada prueba

# Cálculo del producto escalar
indice_rendimiento = np.dot(tiempos_atleta, importancia_pruebas)
print(indice_rendimiento)

44.5


1.	¿Cómo afectaría al resultado si el atleta mejora su tiempo en la prueba de 100m?

	Si el tiempo de 100m disminuye, el índice de rendimiento también disminuirá, ya que la prueba de 100m tiene el mayor peso (0.4) en la evaluación.
    
2.	¿Qué pasaría si le damos más importancia a las pruebas de resistencia?
	
	Al aumentar el peso de las pruebas largas (por ejemplo, 800m y 1500m), los tiempos más altos en estas distancias tendrían un mayor impacto, aumentando probablemente el índice de rendimiento, penalizando más los tiempos largos.
	
3.	¿Cómo se podría utilizar esta métrica para comparar a diferentes atletas?
	
	Comparando el índice de rendimiento de varios atletas: el atleta con el menor índice tendría un desempeño más eficiente según las prioridades establecidas.
	
	Se puede ajustar la importancia relativa de las pruebas para reflejar los objetivos de entrenamiento o características del deporte.


In [9]:
import numpy as np

# 1. Representar los datos como una matriz en NumPy
jugadores = np.array([
    [10, 7, 300, 25, 40],
    [15, 10, 250, 30, 50],
    [5, 12, 280, 20, 35],
    [8, 6, 310, 15, 38],
    [12, 9, 270, 28, 45]
])

# 2. Aplicar la normalización L2 por filas
l2_norm = np.linalg.norm(jugadores, axis=1, keepdims=True)
jugadores_normalizados = jugadores / l2_norm

# Mostrar la matriz normalizada
print(jugadores_normalizados)

[[0.03290221 0.02303155 0.98706643 0.08225554 0.13160886]
 [0.05828815 0.03885877 0.97146918 0.1165763  0.19429384]
 [0.01765627 0.04237506 0.98875136 0.0706251  0.12359392]
 [0.02557216 0.01917912 0.9909212  0.0479478  0.12146776]
 [0.04354749 0.03266062 0.97981848 0.10161081 0.16330308]]


In [10]:
# Datos ficticios de posiciones de 10 pilotos en 5 carreras
posiciones = np.array([
    [1, 3, 5, 7, 2],
    [2, 1, 4, 6, 3],
    [5, 2, 1, 8, 4],
    [3, 5, 2, 1, 6],
    [6, 4, 3, 2, 5],
    [4, 6, 7, 3, 1],
    [8, 7, 6, 5, 9],
    [7, 8, 9, 4, 10],
    [10, 9, 8, 9, 7],
    [9, 10, 10, 10, 8]
])

# 2. Transformación de arrays

# Reorganizar la matriz con reshape (ejemplo: 5 filas y 10 columnas)
posiciones_reshaped = posiciones.reshape(5, 10)

# Convertir la matriz en un array 1D
posiciones_ravel = posiciones.ravel()

# 3. Operaciones aritméticas

# Promedio de posiciones por piloto (axis=1) y por carrera (axis=0)
promedio_por_piloto = np.mean(posiciones, axis=1)
promedio_por_carrera = np.mean(posiciones, axis=0)

# Aplicar una penalización sumando 2 posiciones a cada resultado
posiciones_penalizadas = posiciones + 2
promedio_penalizado = np.mean(posiciones_penalizadas, axis=1)

# 4. Producto escalar (similitud entre dos pilotos, por ejemplo, el piloto 1 y el piloto 2)
producto_escalar = np.dot(posiciones[0], posiciones[1])

# 5. Producto cruzado (comparación de los primeros 3 resultados entre piloto 3 y piloto 4)
producto_cruzado = np.cross(posiciones[2, :3], posiciones[3, :3])

# 6. Extra bonus: Normalización L2 para comparar rendimiento en diferentes circuitos
norma_l2 = np.linalg.norm(posiciones, axis=1, keepdims=True)
posiciones_normalizadas = posiciones / norma_l2

# Mostrar los resultados
{
    "posiciones_reshaped": posiciones_reshaped,
    "posiciones_ravel": posiciones_ravel,
    "promedio_por_piloto": promedio_por_piloto,
    "promedio_por_carrera": promedio_por_carrera,
    "promedio_penalizado": promedio_penalizado,
    "producto_escalar": producto_escalar,
    "producto_cruzado": producto_cruzado,
    "posiciones_normalizadas": posiciones_normalizadas
}

{'posiciones_reshaped': array([[ 1,  3,  5,  7,  2,  2,  1,  4,  6,  3],
        [ 5,  2,  1,  8,  4,  3,  5,  2,  1,  6],
        [ 6,  4,  3,  2,  5,  4,  6,  7,  3,  1],
        [ 8,  7,  6,  5,  9,  7,  8,  9,  4, 10],
        [10,  9,  8,  9,  7,  9, 10, 10, 10,  8]]),
 'posiciones_ravel': array([ 1,  3,  5,  7,  2,  2,  1,  4,  6,  3,  5,  2,  1,  8,  4,  3,  5,
         2,  1,  6,  6,  4,  3,  2,  5,  4,  6,  7,  3,  1,  8,  7,  6,  5,
         9,  7,  8,  9,  4, 10, 10,  9,  8,  9,  7,  9, 10, 10, 10,  8]),
 'promedio_por_piloto': array([3.6, 3.2, 4. , 3.4, 4. , 4.2, 7. , 7.6, 8.6, 9.4]),
 'promedio_por_carrera': array([5.5, 5.5, 5.5, 5.5, 5.5]),
 'promedio_penalizado': array([ 5.6,  5.2,  6. ,  5.4,  6. ,  6.2,  9. ,  9.6, 10.6, 11.4]),
 'producto_escalar': np.int64(73),
 'producto_cruzado': array([-1, -7, 19]),
 'posiciones_normalizadas': array([[0.10660036, 0.31980107, 0.53300179, 0.74620251, 0.21320072],
        [0.24618298, 0.12309149, 0.49236596, 0.73854895, 0.36927447],
